version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      pydantic-runtime:
        patterns:
          - pydantic
          - pydantic-core
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci
