const fs = require('node:fs');
const http = require('node:http');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const CHROME = process.env.IC_BROWSER_BIN || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
function startServer(){const server=http.createServer((request,response)=>{const requestPath=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname);const filePath=path.resolve(ROOT,`.${requestPath}`);if(filePath!==ROOT&&!filePath.startsWith(`${ROOT}${path.sep}`))return response.writeHead(403).end('Forbidden');fs.readFile(filePath,(error,body)=>{if(error)return response.writeHead(error.code==='ENOENT'?404:500).end(error.message);const type={'.css':'text/css','.html':'text/html','.js':'text/javascript','.json':'application/json'}[path.extname(filePath)]||'application/octet-stream';response.writeHead(200,{'Content-Type':`${type}; charset=utf-8`}).end(body);});});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve(server));});}
function debuggerUrl(browser){return new Promise((resolve,reject)=>{let stderr='';const timer=setTimeout(()=>reject(new Error(stderr||'Chrome debugger timeout')),10000);browser.stderr.on('data',chunk=>{stderr+=chunk;const match=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match){clearTimeout(timer);resolve(match[1]);}});});}
async function connect(url){const socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});let nextId=0;const pending=new Map();const events=[];socket.addEventListener('message',message=>{const payload=JSON.parse(message.data);const operation=pending.get(payload.id);if(operation){pending.delete(payload.id);payload.error?operation.reject(new Error(JSON.stringify(payload.error))):operation.resolve(payload.result);}else if(payload.method)events.push(payload);});return{events,send(method,params={},sessionId){const id=++nextId;return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));});}};}
async function evaluate(cdp,sessionId,expression){const result=await cdp.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},sessionId);if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;}
async function waitFor(cdp,sessionId,expression,label,timeout=30000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await evaluate(cdp,sessionId,expression))return;await delay(100);}throw new Error(`Timed out waiting for ${label}`);}
async function backdropClick(cdp,sessionId){await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:2,y:2,button:'left',clickCount:1},sessionId);await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:2,y:2,button:'left',clickCount:1},sessionId);await delay(650);}

async function main(){
  if(!fs.existsSync(CHROME))throw new Error(`Chrome executable not found: ${CHROME}`);
  const server=await startServer();const profile=fs.mkdtempSync(path.join(os.tmpdir(),'ic-dialog-browser-'));const browser=spawn(CHROME,['--headless=new','--disable-gpu','--no-first-run','--remote-allow-origins=*','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let report;
  try{
    const cdp=await connect(await debuggerUrl(browser));const target=await cdp.send('Target.createTarget',{url:'about:blank'});const{sessionId}=await cdp.send('Target.attachToTarget',{targetId:target.targetId,flatten:true});await cdp.send('Page.enable',{},sessionId);await cdp.send('Runtime.enable',{},sessionId);await cdp.send('Log.enable',{},sessionId);await cdp.send('Accessibility.enable',{},sessionId);await cdp.send('Emulation.setDeviceMetricsOverride',{width:1200,height:800,deviceScaleFactor:1,mobile:false},sessionId);const port=server.address().port;
    await cdp.send('Page.navigate',{url:`http://127.0.0.1:${port}/tests/infinite_canvas_ui_dialog_browser_harness.html`},sessionId);await waitFor(cdp,sessionId,"document.documentElement?.dataset.icDialogTestStatus === 'ready'",'Dialog harness ready');
    await evaluate(cdp,sessionId,'window.dialogContract.runMotion()');
    await evaluate(cdp,sessionId,'window.dialogContract.runEscape()');
    await evaluate(cdp,sessionId,'window.dialogContract.openExplicit()');const mediumGeometry=await evaluate(cdp,sessionId,`(()=>{const rect=document.querySelector('#explicit').shadowRoot.querySelector('[part="dialog"]').getBoundingClientRect();return{width:rect.width,viewportWidth:innerWidth,rem:Number.parseFloat(getComputedStyle(document.documentElement).fontSize)}})()`);await backdropClick(cdp,sessionId);const explicitStayedOpen=await evaluate(cdp,sessionId,"document.querySelector('#explicit').open");await evaluate(cdp,sessionId,"document.querySelector('#explicit').hide('cancel')");
    await evaluate(cdp,sessionId,'window.dialogContract.openLight()');const xLargeGeometry=await evaluate(cdp,sessionId,`(()=>{const rect=document.querySelector('#light').shadowRoot.querySelector('[part="dialog"]').getBoundingClientRect();return{width:rect.width,height:rect.height,viewportWidth:innerWidth,viewportHeight:innerHeight,rem:Number.parseFloat(getComputedStyle(document.documentElement).fontSize)}})()`);await backdropClick(cdp,sessionId);const lightClosed=await evaluate(cdp,sessionId,"!document.querySelector('#light').open");
    await evaluate(cdp,sessionId,'window.dialogContract.openConfirmation()');const openTree=await cdp.send('Accessibility.getFullAXTree',{},sessionId);const openDialogs=openTree.nodes.filter(node=>!node.ignored&&node.role?.value==='dialog').map(node=>({role:node.role.value,name:node.name?.value||''}));await evaluate(cdp,sessionId,"document.querySelector('#confirmation').confirmLoading=true");await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'},sessionId);await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'},sessionId);await delay(250);const confirmationStayedOpen=await evaluate(cdp,sessionId,"document.querySelector('#confirmation').open");await evaluate(cdp,sessionId,"document.querySelector('#confirmation').confirmLoading=false;document.querySelector('#confirmation').hide('cancel')");
    const mediumExpected=Math.min(45*mediumGeometry.rem,mediumGeometry.viewportWidth-(2*mediumGeometry.rem));const xLargeExpectedWidth=xLargeGeometry.viewportWidth*.9;const xLargeExpectedHeight=xLargeGeometry.viewportHeight*.92;const dialogSizes=Math.abs(mediumGeometry.width-mediumExpected)<=2&&Math.abs(xLargeGeometry.width-xLargeExpectedWidth)<=2&&Math.abs(xLargeGeometry.height-xLargeExpectedHeight)<=2;
    await evaluate(cdp,sessionId,`window.dialogContract.report.checks.backdrop=${explicitStayedOpen&&lightClosed};window.dialogContract.report.checks.confirmLoading=${confirmationStayedOpen};window.dialogContract.report.checks.sizes=${dialogSizes};window.dialogContract.finish()`);await waitFor(cdp,sessionId,"['passed','failed'].includes(document.documentElement?.dataset.icDialogTestStatus)",'Dialog harness complete');report=JSON.parse(await evaluate(cdp,sessionId,"document.querySelector('#ic-results').textContent"));
    report.sizes={medium:mediumGeometry,xLarge:xLargeGeometry};
    report.accessibility=openDialogs;report.checks.aria=openDialogs.some(node=>node.name==='Delete canvas?');
    await cdp.send('Page.navigate',{url:`http://127.0.0.1:${port}/static/design-system/infinite-canvas-ui/dialog.html`},sessionId);await waitFor(cdp,sessionId,"document.documentElement?.dataset.dialogMatrixStatus === 'ready'",'six Dialog matrix cases',60000);report.matrix=await evaluate(cdp,sessionId,`(()=>{const cards=[...document.querySelectorAll('[data-dialog-case]')];const docs=cards.map(card=>card.querySelector('iframe').contentDocument);return{cases:cards.length,themes:[...new Set(cards.map(x=>x.dataset.theme))].sort(),viewports:[...new Set(cards.map(x=>x.dataset.viewport))].sort(),locales:[...new Set(cards.map(x=>x.dataset.locale))].sort(),motions:[...new Set(cards.map(x=>x.dataset.motion))].sort(),ready:docs.every(doc=>doc.documentElement.dataset.dialogCaseStatus==='ready'),legalCounts:docs.map(doc=>doc.querySelectorAll('.launchers > .scenario').length),overflows:docs.map(doc=>doc.documentElement.scrollWidth>doc.documentElement.clientWidth)};})()`);
    await evaluate(cdp,sessionId,`(async()=>{const doc=document.querySelector('[data-dialog-case] iframe').contentDocument;await doc.querySelector('#reverse-prompt-dialog').show();return true;})()`);
    const modelSelectPoint=await evaluate(cdp,sessionId,`(()=>{const frame=document.querySelector('[data-dialog-case] iframe');const frameRect=frame.getBoundingClientRect();const select=frame.contentDocument.querySelector('#reverse-prompt-dialog ic-select[name="ai-processor-model"]');const rect=select.getBoundingClientRect();return{x:frameRect.left+rect.left+rect.width/2,y:frameRect.top+rect.top+rect.height/2};})()`);
    await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:modelSelectPoint.x,y:modelSelectPoint.y},sessionId);
    await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:modelSelectPoint.x,y:modelSelectPoint.y,button:'left',clickCount:1},sessionId);
    await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:modelSelectPoint.x,y:modelSelectPoint.y,button:'left',clickCount:1},sessionId);
    await delay(80);
    report.reversePromptModelPointerFocus=await evaluate(cdp,sessionId,`(()=>{const doc=document.querySelector('[data-dialog-case] iframe').contentDocument;const select=doc.querySelector('#reverse-prompt-dialog ic-select[name="ai-processor-model"]');const style=getComputedStyle(select.shadowRoot.querySelector('[part~="combobox"]'));return{modality:doc.documentElement.dataset.icInputModality,focused:doc.activeElement===select,open:select.open,outlineVisible:style.outlineStyle!=='none'&&Number.parseFloat(style.outlineWidth)>0&&style.outlineColor!=='rgba(0, 0, 0, 0)'};})()`);
    await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},sessionId);
    await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},sessionId);
    await delay(80);
    report.reversePromptModelKeyboardFocus=await evaluate(cdp,sessionId,`(()=>{const doc=document.querySelector('[data-dialog-case] iframe').contentDocument;const select=doc.querySelector('#reverse-prompt-dialog ic-select[name="ai-processor-model"]');select.focus();const style=getComputedStyle(select.shadowRoot.querySelector('[part~="combobox"]'));return{modality:doc.documentElement.dataset.icInputModality,focused:doc.activeElement===select,outlineVisible:style.outlineStyle!=='none'&&Number.parseFloat(style.outlineWidth)>0&&style.outlineColor!=='rgba(0, 0, 0, 0)'};})()`);
    await evaluate(cdp,sessionId,`(()=>{const doc=document.querySelector('[data-dialog-case] iframe').contentDocument;doc.querySelector('#reverse-prompt-dialog').open=false;return true;})()`);
    await delay(650);
    report.reversePrompt=await evaluate(cdp,sessionId,`(async()=>{const doc=document.querySelector('[data-dialog-case] iframe').contentDocument;const dialog=doc.querySelector('#reverse-prompt-dialog');await dialog.show();const photo=dialog.querySelector('[data-template-id="photo"]');photo.click();await new Promise(resolve=>setTimeout(resolve,80));const select=dialog.querySelector('ic-select[name="ai-processor-model"]');select.value='gpt-5.5';select.dispatchEvent(new Event('change',{bubbles:true,composed:true}));await new Promise(resolve=>setTimeout(resolve,80));let confirmation=null;dialog.addEventListener('ic-confirm',event=>{confirmation=event.detail;event.preventDefault();},{once:true});await dialog.confirm();const rect=dialog.shadowRoot.querySelector('[part="dialog"]').getBoundingClientRect();const result={status:dialog.dataset.icContractStatus,size:dialog.size,width:rect.width,selectedTemplates:[...dialog.querySelectorAll('[data-template-id][checked]')].map(item=>item.dataset.templateId),selectedModel:dialog.selectedModel,templateHeadingCount:dialog.querySelectorAll('[data-template-id] ic-heading[subtitle]').length,templateDecorativeIconCount:dialog.querySelectorAll('[data-template-id] [data-ic-checkbox-icon]').length,directImage:Boolean(dialog.querySelector('[data-ai-processor-layout="reverse-prompt"] > [data-ai-processor-source]')),closeDisplay:getComputedStyle(dialog.shadowRoot.querySelector('[part="close-button"]')).display,confirmation,openAfterPreventedConfirm:dialog.open};await dialog.hide('test');return result;})()`);
    report.consoleErrors=cdp.events.flatMap(event=>event.method==='Runtime.exceptionThrown'?[event.params.exceptionDetails?.exception?.description||event.params.exceptionDetails?.text]:event.method==='Runtime.consoleAPICalled'&&event.params.type==='error'?[event.params.args?.map(arg=>arg.value||arg.description).join(' ')]:[]);
    report.checks.matrix=report.matrix.cases===6&&report.matrix.ready&&report.matrix.legalCounts.every(value=>value===12)&&report.matrix.overflows.every(value=>!value);
    report.checks.reversePromptModelFocus=report.reversePromptModelPointerFocus.modality==='pointer'&&report.reversePromptModelPointerFocus.open&&!report.reversePromptModelPointerFocus.outlineVisible&&report.reversePromptModelKeyboardFocus.modality==='keyboard'&&report.reversePromptModelKeyboardFocus.focused&&report.reversePromptModelKeyboardFocus.outlineVisible;
    report.checks.reversePrompt=report.reversePrompt.status==='ready'&&report.reversePrompt.size==='medium'&&report.reversePrompt.selectedTemplates.length===1&&report.reversePrompt.selectedTemplates[0]==='photo'&&report.reversePrompt.selectedModel==='gpt-5.5'&&report.reversePrompt.templateHeadingCount===2&&report.reversePrompt.templateDecorativeIconCount===0&&report.reversePrompt.directImage&&report.reversePrompt.closeDisplay==='none'&&report.reversePrompt.confirmation?.templateId==='photo'&&report.reversePrompt.confirmation?.modelId==='gpt-5.5'&&report.reversePrompt.openAfterPreventedConfirm;
    report.checks.console=report.consoleErrors.length===0;report.browser=await cdp.send('Browser.getVersion');
  }finally{browser.kill('SIGTERM');server.close();}
  process.stdout.write(`${JSON.stringify(report,null,2)}\n`);if(!Object.values(report.checks).every(Boolean))process.exitCode=1;
}
main().catch(error=>{console.error(error);process.exitCode=1;});
