const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const baseUrl = process.env.SMART_CANVAS_BASE_URL || 'http://127.0.0.1:8799';
(async () => {
 const browser=await chromium.launch({headless:true,executablePath:process.env.SMART_CANVAS_BROWSER || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try {
  const page=await browser.newPage({viewport:{width:1280,height:1800}});
  await page.goto(`${baseUrl}/static/design-system/infinite-canvas-ui/feedback-progress-case.html`);
  const runtime=page.locator('.node-runtime-sample ic-badge').first();
  await runtime.scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('.node-runtime-sample ic-badge[loading]')?.shadowRoot.querySelector('canvas')?.dataset.motionState==='running');
  const runtimePixel=()=>runtime.evaluate(el=>el.shadowRoot.querySelector('canvas').toDataURL());
  const first=await runtimePixel();
  await page.waitForTimeout(180);
  assert.notEqual(await runtimePixel(),first,'runtime badge animates');
  await page.evaluate(()=>document.documentElement.dataset.uiMotion='reduced');
  await page.waitForTimeout(80);
  const pixels=await page.evaluate(()=>[...document.querySelectorAll('ic-generation-pending')].map(el=>el.shadowRoot.querySelector('.generation-pending-orb').toDataURL()));
  assert.equal(pixels.length,3);
  assert(pixels.every(p=>p===pixels[0]),'queued/generating text/image/video share one breathing preset');
  assert.equal(await runtimePixel(),pixels[0],'runtime status uses exactly the pending video ring');
  const frozen=await runtimePixel();
  await page.waitForTimeout(150);
  assert.equal(await runtimePixel(),frozen);
  await runtime.evaluate(el=>{window.runtimeOrb=el.shadowRoot.querySelector('canvas');el.textContent='14s';});
  assert(await runtime.evaluate(el=>el.shadowRoot.querySelector('canvas')===window.runtimeOrb),'timer copy updates preserve animation identity');
  await page.evaluate(()=>document.documentElement.dataset.uiTheme='dark');
  await page.waitForTimeout(80);
  assert.notEqual(await runtimePixel(),frozen,'ring adapts to dark theme');
  await page.evaluate(()=>delete document.documentElement.dataset.uiMotion);
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>document.querySelector('.node-runtime-sample ic-badge[loading]').shadowRoot.querySelector('canvas').dataset.motionState==='static');
  assert.equal(await runtime.evaluate(el=>el.shadowRoot.querySelector('canvas').dataset.motionState),'static');
  assert(await page.evaluate(()=>[...document.querySelectorAll('ic-generation-pending')].every(el=>el.shadowRoot.querySelector('.generation-pending-orb').dataset.motionState==='static')), 'all pending indicators honor the system preference together');
  assert.equal(await runtimePixel(),await page.evaluate(()=>document.querySelector('#generation-pending-video').shadowRoot.querySelector('.generation-pending-orb').toDataURL()));
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.waitForTimeout(80);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
  await page.waitForTimeout(80);
  assert.equal(await runtime.evaluate(el=>el.shadowRoot.querySelector('canvas').dataset.motionState),'paused');
  const paused=await runtimePixel();
  await page.waitForTimeout(150);
  assert.equal(await runtimePixel(),paused);
  await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
  await runtime.evaluate(el=>el.removeAttribute('loading'));
  assert.equal(await runtime.locator('canvas').count(),0,'completion releases the running indicator');
  const completed=page.locator('.node-runtime-sample ic-badge').last();
  assert.equal(await completed.locator('canvas').count(),0,'completed status stays still');
  await runtime.evaluate(el=>el.setAttribute('loading',''));
  await page.waitForTimeout(80);
  await runtime.evaluate(el=>{window.removedOrb=el.shadowRoot.querySelector('canvas');el.remove();});
  const detached=await page.evaluate(()=>window.removedOrb.toDataURL());
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(()=>window.removedOrb.toDataURL()),detached,'detached runtime badge releases its clock');
  console.log('Unified generation ring: identical preset, runtime animation, timer identity, light/dark, project/system reduced motion, background pause, completion and disconnect passed.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
