/* Runs against the real page in issue_38_layer_dialog_fixture.cjs only. */
window.runLayerDialogChecks = async function () {
 const result=document.querySelector('#fixture-result');
 let passed=0;
 const check=(condition,message)=>{if(!condition)throw new Error(message);passed++;};
 const settle=()=>new Promise(resolve=>setTimeout(resolve,100));
 const type=(element,value)=>{element.value=value;element.dispatchEvent(new Event('input',{bubbles:true}));};
 const choose=(element,value,event=element.matches('ic-segmented-control')?'ic-change':'change')=>{element.value=value;element.setAttribute('value',value);element.dispatchEvent(new CustomEvent(event,{bubbles:true,detail:{value}}));};
 try{
  const primary=nodes.find(n=>n.id==='layer-source').images.find(image=>image.media_id==='layer-source-media');
  if(primary) canvasMutation.update({nodeId:'layer-source',mutate:node=>{node.images=[primary];},options:{render:false,select:false}});
  const initial=await fetch('/fixture/state').then(r=>r.json());
  await openAiProcessorForSmartImage('layer-decomposition','layer-source',0);await settle();
  const dialog=document.querySelector('ic-ai-processor-dialog');
  check(dialog.querySelectorAll('[data-layer-mode] > button').length===2,'Two modes');
  if(dialog.querySelector('[data-layer-mode]').getAttribute('value')==='regions'){choose(dialog.querySelector('[data-layer-mode]'),'intelligent','ic-change');await settle();}
  check(dialog.querySelectorAll('[name="layer-preset"] > button').length===4,'Four presets without custom');
  choose(dialog.querySelector('[name="layer-preset"]'),'auto');await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value===''&&dialog.detail().prompt==='','Automatic starts and submits without a generated prompt');
  check(dialog.querySelector('[name="layer-preset"]').localName==='ic-segmented-control'&&dialog.querySelector('[name="layer-resolution"]').localName==='ic-segmented-control','Both choices use segmented controls');
  check(!dialog.querySelector('[data-layer-hint]'),'No recognition explanation under presets');
  choose(dialog.querySelector('[name="layer-resolution"]'),'1K');await settle();
  check(dialog.detail().layerResolution==='1K','Segmented resolution change reaches submission');
  const granularity=dialog.querySelector('[name="layer-preset"]'),firstChoice=granularity.querySelector('button').getBoundingClientRect();
  check(firstChoice.width>=granularity.clientWidth*.4,'Long option labels have space without overlap');
  choose(dialog.querySelector('[name="layer-preset"]'),'subject-background');await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value.length>0,'Nonautomatic preset still supplies a prompt');
  choose(dialog.querySelector('[name="layer-preset"]'),'auto');await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value==='','Returning to automatic leaves the prompt empty');
  choose(dialog.querySelector('[name="layer-preset"]'),'objects');await settle();
  type(dialog.querySelector('[name="layer-prompt"]'),'Before a vetoed close');
  dialog.addEventListener('ic-hide',event=>event.preventDefault(),{once:true});
  await dialog.hide('cancel');await settle();
  check(dialog.open,'Canceled close keeps dialog open');
  type(dialog.querySelector('[name="layer-prompt"]'),'Keep title and note separate — 草稿');
  check(dialog.detail().prompt==='Keep title and note separate — 草稿','Canceled close keeps authoring listeners alive');
  await dialog.requestClose(dialog);await settle();
  check(!dialog.open,'Native close path saves and closes');
  await openAiProcessorForSmartImage('layer-decomposition','layer-source',0);await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value==='Keep title and note separate — 草稿','Close/reopen draft');
  window.StudioI18n.set('en');await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value.includes('草稿'),'Language preserves authored text');
  choose(dialog.querySelector('[data-layer-mode]'),'regions','ic-change');await settle();
  dialog.querySelector('[data-layer-clear]').click();await settle();
  dialog.querySelector('[data-layer-add]').click();await settle();
  check(dialog.querySelectorAll('cropper-selection:not([hidden])').length===1,'Add region');
  check(dialog.querySelector('[data-layer-prompt-preview]').textContent.includes('<bbox>375 375 625 625</bbox>'),'Source coordinate normalization');
  const coordinate=(key,value)=>type(dialog.querySelector(`[data-layer-coordinate="${key}"]`),String(value));
  coordinate('x',200);coordinate('y',200);coordinate('width',1400);coordinate('height',200);await settle();
  check(dialog.querySelector('[data-layer-prompt-preview]').textContent.includes('<bbox>100 200 800 400</bbox>'),'Exact original-pixel example');
  const numeric=dialog.querySelector('[data-layer-coordinate="width"]');
  type(numeric,'4000');numeric.dispatchEvent(new Event('change'));await settle();
  check(Number(numeric.value)===1400,'Out-of-bounds numeric recovery');
  const canvas=dialog.querySelector('[data-layer-canvas]');
  canvas.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',shiftKey:true,bubbles:true,composed:true}));await settle();
  check(Number(dialog.querySelector('[data-layer-coordinate="x"]').value)===210,'Scoped keyboard movement');
  const pointer=(target,event,x,y)=>target.dispatchEvent(new PointerEvent(event,{bubbles:true,composed:true,pointerId:7,pointerType:'mouse',button:0,buttons:event==='pointerup'?0:1,clientX:x,clientY:y}));
  dialog.querySelector('[data-layer-clear]').click();await settle();
  const bounds=canvas.getBoundingClientRect(),draw=canvas.querySelector('[data-layer-draw]');
  pointer(draw,'pointerdown',bounds.left+20,bounds.top+20);
  pointer(document,'pointermove',bounds.left+60,bounds.top+20);
  pointer(document,'pointerup',bounds.left+60,bounds.top+20);await settle();
  check(!canvas.querySelector('cropper-selection[data-region-id]')&&!dialog.querySelector('[data-layer-prompt-preview]').textContent.includes('<bbox>'),'Zero-area drag creates no selection');
  pointer(canvas.querySelector('[data-layer-draw]'),'pointerdown',bounds.left+bounds.width*.8,bounds.top+bounds.height*.8);
  pointer(document,'pointermove',bounds.left+bounds.width*.7,bounds.top+bounds.height*.7);
  pointer(document,'pointermove',bounds.left+bounds.width*.2,bounds.top+bounds.height*.2);
  pointer(document,'pointerup',bounds.left+bounds.width*.2,bounds.top+bounds.height*.2);await settle();
  check(dialog.querySelector('[data-layer-prompt-preview]').textContent.includes('<bbox>200 200 800 800</bbox>'),'Reverse drag keeps both pointer endpoints');
  for(const direction of ['n','e','s','w','ne','nw','se','sw']){
   const handle=canvas.querySelector(`cropper-selection[active] [action="${direction}-resize"]`);
   const r=handle.getBoundingClientRect(),before=dialog.querySelector('[data-layer-prompt-preview]').textContent;
   pointer(handle,'pointerdown',r.x+r.width/2,r.y+r.height/2);
   pointer(document,'pointermove',r.x+r.width/2+3,r.y+r.height/2+3);
   pointer(document,'pointerup',r.x+r.width/2+3,r.y+r.height/2+3);await settle();
   check(dialog.querySelector('[data-layer-prompt-preview]').textContent!==before,`${direction} resize`);
  }
  const beforeCancel=dialog.querySelector('[data-layer-prompt-preview]').textContent;
  const move=canvas.querySelector('cropper-selection[active] [action="move"]'),r=move.getBoundingClientRect();
  pointer(move,'pointerdown',r.x+20,r.y+20);pointer(document,'pointermove',r.x+30,r.y+30);
  canvas.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,composed:true,cancelable:true}));
  pointer(document,'pointerup',r.x+30,r.y+30);await settle();
  check(dialog.open&&dialog.querySelector('[data-layer-prompt-preview]').textContent===beforeCancel,'Escape restores gesture without closing');
  type(dialog.querySelector('[name="layer-description"]'),'note only');
  type(dialog.querySelector('[name="layer-supplement"]'),'Preserve lettering');
  const region=dialog.querySelector('[name="layer-region"]').value;
  dialog.querySelector('[data-layer-add]').click();await settle();
  check(dialog.querySelectorAll('cropper-selection:not([hidden])').length===2,'Overlapping regions');
  dialog.querySelector('[data-layer-delete]').click();await settle();
  check(dialog.querySelector('[name="layer-region"]').value===region,'Stable identity after delete');
  choose(dialog.querySelector('[data-layer-mode]'),'intelligent','ic-change');await settle();
  check(dialog.querySelector('[name="layer-prompt"]').value.includes('草稿'),'Mode preserves intelligent draft');
  choose(dialog.querySelector('[data-layer-mode]'),'regions','ic-change');await settle();
  check(dialog.querySelector('[name="layer-description"]').value==='note only','Mode preserves region description');
  await dialog.hide('cancel');await settle();
  await canvasPersistence.checkpoint();
  const saved=await fetch('/fixture/state').then(r=>r.json());
  const draft=saved.canvas.nodes.find(n=>n.id==='layer-source').layerDecompositionDrafts['media_id:layer-source-media'];
  check(draft.mode==='regions'&&draft.regions.length===1&&draft.supplement==='Preserve lettering','Confirmed Canvas persistence');
  check(saved.submissions.length===initial.submissions.length,'No implicit generation');
  await openAiProcessorForSmartImage('layer-decomposition','layer-source',0);await settle();
  check(dialog.querySelector('[name="layer-description"]').value==='note only','Reopen regions');
  for(let i=1;i<16;i++){dialog.querySelector('[data-layer-add]').click();await settle();}
  dialog.querySelector('[data-layer-add]').click();await settle();
  check(dialog.querySelectorAll('cropper-selection:not([hidden])').length===16,'Region limit');
  dialog.querySelector('[data-layer-clear]').click();await settle();
  check(dialog.confirmAction.disabled,'Empty regions cannot submit');
  dialog.querySelector('[data-layer-add]').click();await settle();
  const finalPrompt=dialog.querySelector('[data-layer-prompt-preview]').textContent;
  dialog.confirm();dialog.confirm();await new Promise(resolve=>setTimeout(resolve,1000));
  const submitted=await fetch('/fixture/state').then(r=>r.json());
  check(submitted.submissions.length===initial.submissions.length+1,'Exactly one task on double submit');
  const request=submitted.submissions.at(-1);
  check(request.prompt===finalPrompt,'Compiled region prompt submitted unchanged');
  check(JSON.stringify(request).includes('/fixture/source.svg')&&!JSON.stringify(request).includes('data:image'),'Original image submitted');
  await openAiProcessorForSmartImage('layer-decomposition','layer-source',0);await settle();
  check(dialog.querySelectorAll('cropper-selection:not([hidden])').length===1,'Draft survives generation failure');
  const modelControl=dialog.querySelector('[name="ai-processor-model"]'),firstModel=dialog.selectedModel;
  choose(modelControl,'apimart-secondary|seedream-layer-pro');await settle();
  check(dialog.confirmAction.disabled&&dialog.querySelector('[data-layer-status]').textContent.length>0,'Unreviewed model bbox disabled');
  choose(dialog.querySelector('[name="ai-processor-model"]'),firstModel);await settle();
  const originalUrl=dialog.sourceImage;
  dialog.sourceImage='/fixture/missing-image.png';await new Promise(resolve=>setTimeout(resolve,300));
  check(dialog.confirmAction.disabled&&!dialog.querySelector('[data-layer-retry]').hidden,'Image failure blocks regions and offers retry');
  dialog.sourceImage=originalUrl;await settle();
  check(!dialog.confirmAction.disabled,'Image recovery preserves valid regions');
  const source=nodes.find(n=>n.id==='layer-source'),originalImages=JSON.parse(JSON.stringify(source.images));
  canvasMutation.update({nodeId:source.id,mutate:node=>{node.images=[{...originalImages[0],media_id:'other-media'},...originalImages];},options:{render:false,select:false}});
  type(dialog.querySelector('[name="layer-supplement"]'),'Reordered original');
  check(flushLayerDecompositionDraft(),'Reordered media resolves by identity');
  check(nodes.find(n=>n.id===source.id).layerDecompositionDrafts['media_id:layer-source-media'].supplement==='Reordered original','Reorder preserves original draft');
  await dialog.hide('cancel');await settle();
  await openAiProcessorForSmartImage('layer-decomposition',source.id,0);await settle();
  check(dialog.querySelector('[name="layer-preset"]').getAttribute('value')==='auto','Other media starts fresh');
  await dialog.hide('cancel');await settle();
  await openAiProcessorForSmartImage('layer-decomposition',source.id,1);await settle();
  check(dialog.querySelector('[name="layer-supplement"]').value==='Reordered original','Original media draft restores');
  canvasMutation.update({nodeId:source.id,mutate:node=>{node.layerDecompositionDrafts['media_id:layer-source-media'].supplement='Remote edit';},options:{render:false,select:false}});
  type(dialog.querySelector('[name="layer-supplement"]'),'Local edit');
  check(!flushLayerDecompositionDraft(),'Concurrent field conflict is rejected');
  check(nodes.find(n=>n.id===source.id).layerDecompositionDrafts['media_id:layer-source-media'].supplement==='Remote edit','Conflict does not overwrite other edit');
  await dialog.hide('cancel');await settle();
  check(dialog.open,'Conflicting draft blocks ordinary close');
  await new Promise(resolve=>{dialog.addEventListener('ic-after-hide',resolve,{once:true});dialog.querySelector('[data-layer-discard]').click();});
  check(!dialog.open,'Conflict permits explicit discard and close');
  await openAiProcessorForSmartImage('layer-decomposition',source.id,1);await settle();
  canvasMutation.update({nodeId:source.id,mutate:node=>{node.images=[{...originalImages[0],media_id:'replacement'}];},options:{render:false,select:false}});
  type(dialog.querySelector('[name="layer-supplement"]'),'Must not follow replacement');
  check(!flushLayerDecompositionDraft(),'Replacement refuses stale save');
  await new Promise(resolve=>{dialog.addEventListener('ic-after-hide',resolve,{once:true});dialog.querySelector('[data-layer-discard]').click();});
  canvasMutation.update({nodeId:source.id,mutate:node=>{node.images=originalImages;},options:{render:false,select:false}});
  await canvasPersistence.checkpoint();
  await openAiProcessorForSmartImage('layer-decomposition',source.id,0);await settle();
  check(dialog.querySelector('[name="layer-supplement"]').value==='Remote edit','Replacement did not change original saved draft');
  result.textContent=`PASS: ${passed} page contracts`;
 }catch(error){result.textContent=`FAIL: ${error.message}`;console.error(error);}
};
