/* Real-page acceptance: node tests/issue_38_layer_dialog_fixture.cjs --editor */
window.runLayerEditorChecks = async function () {
    const result = document.getElementById('fixture-result');
    let passed = 0;
    const check = (ok, message) => { if(!ok) throw new Error(message); passed++; };
    const settle = () => new Promise(resolve => setTimeout(resolve, 120));
    const el = id => document.getElementById(id);
    try {
        selectedId = 'layer-result'; selectedIds = []; selectedImage = {nodeId:'',index:-1};
        render(); await settle();
        const portal = el('smartNodeFloatingPortal');
        const commands = () => [...portal.querySelectorAll('[data-smart-node-action]')];
        check(portal.classList.contains('open') && portal.querySelector('ic-smart-node-toolbar'), 'Selected layer node shows public toolbar');
        check(commands().map(button => button.dataset.smartNodeAction).join(',') === 'preview,download-psd', 'Only preview and PSD download');
        window.StudioI18n.set('en'); await settle();
        check(commands().map(button => button.textContent.trim()).join('|') === 'Preview|Download PSD', 'English node toolbar');
        window.StudioI18n.set('zh'); await settle();
        check(commands().map(button => button.textContent.trim()).join('|') === '预览|下载 PSD', 'Chinese node toolbar');
        const beforeExports = (await fetch('/fixture/state').then(response => response.json())).psdExports.length;
        const download = portal.querySelector('[data-smart-node-action="download-psd"]');
        download.click();
        check(download.disabled, 'Node toolbar download busy');
        for(let attempt=0;attempt<40 && download.disabled;attempt++) await settle();
        check(!download.disabled, 'Node toolbar download recovers');
        const exports = (await fetch('/fixture/state').then(response => response.json())).psdExports;
        check(exports.length === beforeExports + 1 && exports.at(-1).nodeId === 'layer-result', 'PSD export targets selected layer node');
        check(!imageStudioDialogOpen(), 'Download works directly from canvas');
        portal.querySelector('[data-smart-node-action="preview"]').click(); await settle();
        check(imageStudioDialogOpen() && el('imageEditModal').classList.contains('layer-decomposition-edit-mode'), 'Preview opens layer editor');
        const editorDownload = el('layerDecompositionPsdDownload');
        editorDownload.click();
        check(editorDownload.disabled, 'Editor passes its own download button');
        for(let attempt=0;attempt<40 && editorDownload.disabled;attempt++) await settle();
        check(!editorDownload.disabled, 'Editor download busy state recovers');
        const editorExports = (await fetch('/fixture/state').then(response => response.json())).psdExports;
        check(editorExports.length === beforeExports + 2, 'Both download entry points export the layer node');
        const toolbar = el('layerDecompositionEditorTools');
        const buttonColor = button => getComputedStyle(button.shadowRoot.querySelector('[part~="base"]')).color;
        const originalTheme = document.documentElement.dataset.uiTheme;
        try {
            for(const theme of ['light', 'dark']) {
                document.documentElement.dataset.uiTheme = theme;
                await settle();
                const zoomColor = buttonColor(toolbar.querySelector('[icon="zoom-in"]'));
                check(buttonColor(el('layerDecompositionPsdDownload')) === zoomColor, `${theme}: enabled download uses normal foreground`);
                check(buttonColor(el('layerDecompositionCompareToggle')) === zoomColor, `${theme}: enabled compare uses normal foreground`);
            }
        } finally {
            if(originalTheme === undefined) delete document.documentElement.dataset.uiTheme;
            else document.documentElement.dataset.uiTheme = originalTheme;
        }
        const composite = el('layerDecompositionEditorComposite');
        const before = composite.getBoundingClientRect();
        check(toolbar.contains(el('layerDecompositionPsdDownload')), 'Download in bar');
        check(!document.querySelector('.layer-decomposition-editor-panel').contains(el('layerDecompositionPsdDownload')), 'No panel download');
        check(Math.abs(before.width / before.height - 2) < .01, 'Manifest aspect ratio');
        check(!el('layerDecompositionCompareToggle').disabled, 'Original source available');
        toolbar.querySelector('[icon="zoom-in"]').click();
        check(el('layerDecompositionZoomLabel').textContent === '110%', 'Zoom in label');
        check(Math.abs(composite.getBoundingClientRect().width / before.width - 1.1) < .01, 'Composite actually scales');
        toolbar.querySelector('[icon="zoom-out"]').click();
        check(el('layerDecompositionZoomLabel').textContent === '100%', 'Zoom out');
        el('layerDecompositionCompareToggle').click();
        await settle();
        check(!el('layerDecompositionCompareImage').hidden && el('layerDecompositionCompareImage').naturalWidth > 0, 'Original image loaded');
        check(el('layerDecompositionCompareImage').getAttribute('src').includes('/fixture/source.svg'), 'Source instead of generated base');
        check(getComputedStyle(el('layerDecompositionCompareHandle')).display !== 'none', 'Compare handle visible');
        el('layerDecompositionCompareHandle').dispatchEvent(new KeyboardEvent('keydown', {key:'ArrowRight',bubbles:true}));
        check(el('layerDecompositionCompareHandle').getAttribute('aria-valuenow') === '55', 'Keyboard comparison position');
        check(composite.style.getPropertyValue('--compare-pos') === '55%', 'Original clipping position follows handle');
        applyLayerDecompositionEditorAction('note', 'visibility');
        check(el('layerDecompositionEditorLayers').querySelectorAll('.is-hidden').length === 1, 'Layer visibility updates composite');
        check(!el('layerDecompositionCompareImage').hidden, 'Comparison survives layer update');
        applyLayerDecompositionEditorAction('note', 'visibility');
        toolbar.querySelector('[icon="zoom-in"]').click();
        toolbar.querySelector('[icon="fit"]').click();
        check(el('layerDecompositionZoomLabel').textContent === '100%' && composite.style.transform.includes('translate(0px, 0px)'), 'Fit restores zoom and pan');
        window.StudioI18n.set('en'); await settle();
        check(el('layerDecompositionPsdDownload').textContent.includes('Download PSD'), 'English download');
        check(el('layerDecompositionCompareToggle').textContent.includes('Compare'), 'English comparison');
        check(el('layerDecompositionZoomLabel').getAttribute('label') === 'Preview zoom', 'English accessible zoom');
        window.StudioI18n.set('zh'); await settle();
        check(el('layerDecompositionCompareToggle').textContent.includes('对比原图'), 'Chinese comparison');
        closeImageEditor(); await settle();
        openImageEditor('layer-source', 0); await settle();
        check(toolbar.hidden && !el('imagePreviewTools').hidden, 'Ordinary preview restores its toolbar');
        closeImageEditor(); await settle();
        openLayerDecompositionEditor({nodeId:'layer-result'}); await settle();
        await new Promise(resolve => setTimeout(resolve, 400));
        check(imageStudioDialogOpen(), 'Reopen survives pending hide animation');
        check(el('layerDecompositionCompareImage').hidden && el('layerDecompositionZoomLabel').textContent === '100%', 'Reopen resets transient viewing state');
        el('layerDecompositionCompareToggle').click();
        el('layerDecompositionCompareImage').dispatchEvent(new Event('error'));
        check(el('layerDecompositionCompareImage').hidden, 'Failed original image exits comparison');
        el('layerDecompositionCompareToggle').click(); await settle();
        check(!el('layerDecompositionCompareImage').hidden, 'Original image retry');
        el('layerDecompositionCompareToggle').click();
        const source = nodes.find(node => node.id === 'layer-source');
        const media = source.images;
        source.images = [];
        syncLayerDecompositionView();
        await settle();
        check(el('layerDecompositionCompareToggle').disabled && el('layerDecompositionCompareImage').hidden, 'Missing source disables comparison');
        check(buttonColor(el('layerDecompositionCompareToggle')) !== buttonColor(toolbar.querySelector('[icon="zoom-in"]')), 'Unavailable comparison keeps disabled color');
        source.images = media;
        syncLayerDecompositionView();
        check(!el('layerDecompositionCompareToggle').disabled, 'Source recovery');
        result.textContent = `PASS ${passed} editor checks`;
    } catch(error) { result.textContent = `FAIL after ${passed}: ${error.message}`; console.error(error); }
};
